on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build vagrant box

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install apt-get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: ubuntu-21-10.pkr.hcl

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ubuntu-21-10.pkr.hcl
        env:
          PACKER_LOG: 1
