on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build vagrant box

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install packer and dependencies
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install -y packer qemu-system-x86

      - name: Validate Template
        run: |
          packer validate ubuntu-21-10.pkr.hcl

      - name: Build Artifact
        run: |
          packer build -color=false -on-error=abort ubuntu-21-10.pkr.hcl
        env:
          PACKER_LOG: 1
