on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build vagrant box

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install qemu
        run: |
          sudo apt-get install -y qemu-system-x86

      - name: Validate Template
        run: |
          packer validate ubuntu-21-10.pkr.hcl

      - name: Build Artifact
        run: |
          packer build -color=false -on-error=abort ubuntu-21-10.pkr.hcl
        env:
          PACKER_LOG: 1
